GET http://localhost:8080/api/employee/2/cars
Accept: application/json

###
GET http://localhost:8080/api/car/1
Accept: application/json

###


POST http://localhost:8080/api/employee/2/car
Content-Type: application/json

{
  "numberPlate": "D DD 200",
  "model": "Supra",
  "hp": 240,
  "buildYear": 2009
}
###

PUT http://localhost:8080/api/car/1
Content-Type: application/json

{
  "numberPlate": "ME NV 400",
  "model": "7er Bmw",
  "hp": 500,
  "buildYear": 2019
}

###
DELETE http://localhost:8080/api/employee/2/cars
Accept: application/json